### PR TITLE
Add information about magento migration

### PR DESCRIPTION
**Pull request by wodor**

### CODE REVIEW

**Comment by shieldo** [comment]
This is Gant-specific documentation - we would need to have a location that this could be added to.

**Comment by wodor** [comment]
Maybe it should live in assembla wiki ?

**Comment by shieldo** [comment]
@astalker Has this, or can this be added to GANT docs?

**Comment by astalker** [comment]
Added the the Gant github wiki now - https://github.com/usemarkup/shop-gant/wiki/Magento-Import

**Pull request closed without merging**
